### PR TITLE
fix: README.md Closes #279

### LINKED ISSUE #279: Provider does not load config values
### What happened?

Config values `gitlab:token` and `gitlab:base_url` are not correctly loaded by the Provider.

I tried by putting the configuration values both in `Pulumi.yaml` and `Pulumi.dev.yaml` files but none of them worked, the only way I got it working is to explicitly configure the provider in the code.

### Expected Behavior

To have the GitLab provider configured with the values provided in the `Pulumi.<stack>.yaml` file.

### Steps to reproduce

Set 
```yaml
gitlab:base_url: https://<gitlab-host>/api/v4/
gitlab:token:
    secure: <encrypted-token>
```
in your `Pulumi.<stack>.yaml` file.

Run `pulumi up` and you will get the following error:
```
error: Failed to create GitLab Client from provider configuration: The provider failed to create a new GitLab Client from the given configuration: GET https://gitlab.com/api/v4/user: 401 {message: 401 Unauthorized}
```

### Output of `pulumi about`

CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.102.0
azuread       5.37.0
flux          0.22.2
gcp           6.56.0
gitlab        5.0.2
kubernetes    3.27.1
nodejs        unknown
random        4.13.0
tls           4.10.0

Host     
OS       darwin
Version  12.3
Arch     arm64

This project is written in nodejs: executable='/Users/mattia.devivo@igenius.ai/.nvm/versions/node/v18.13.0/bin/node' version='v18.13.0'

Current Stack: organization/infrastructure/dev

TYPE                                                         URN
pulumi:pulumi:Stack                                          urn:pulumi:dev::infrastructure::pulumi:pulumi:Stack::infrastructure-dev
custom:gcp:GcpServiceAccount                                 urn:pulumi:dev::infrastructure::custom:gcp:GcpServiceAccount::gcp-service-account
pulumi:providers:flux                                        urn:pulumi:dev::infrastructure::pulumi:providers:flux::default_0_22_2
pulumi:providers:gitlab                                      urn:pulumi:dev::infrastructure::pulumi:providers:gitlab::gitlab-provider
pulumi:providers:random                                      urn:pulumi:dev::infrastructure::pulumi:providers:random::default_4_13_0
random:index/randomPassword:RandomPassword                   urn:pulumi:dev::infrastructure::random:index/randomPassword:RandomPassword::postgres-password
pulumi:providers:tls                                         urn:pulumi:dev::infrastructure::pulumi:providers:tls::default_4_10_0
pulumi:providers:gcp                                         urn:pulumi:dev::infrastructure::pulumi:providers:gcp::default_6_56_0
tls:index/privateKey:PrivateKey                              urn:pulumi:dev::infrastructure::tls:index/privateKey:PrivateKey::bastion-ssh-key
pulumi:providers:azure-native                                urn:pulumi:dev::infrastructure::pulumi:providers:azure-native::default_1_102_0
gcp:serviceAccount/account:Account                           urn:pulumi:dev::infrastructure::gcp:serviceAccount/account:Account::aks-service-account
azure-native:resources:ResourceGroup                         urn:pulumi:dev::infrastructure::azure-native:resources:ResourceGroup::crystal-dev
azure-native:resources:ResourceGroup                         urn:pulumi:dev::infrastructure::azure-native:resources:ResourceGroup::crystal-aks-dev
pulumi:providers:kubernetes                                  urn:pulumi:dev::infrastructure::pulumi:providers:kubernetes::default_3_27_1
azure-native:operationalinsights:Workspace                   urn:pulumi:dev::infrastructure::azure-native:operationalinsights:Workspace::aks-dev-logsanalytics
gcp:serviceAccount/key:Key                                   urn:pulumi:dev::infrastructure::gcp:serviceAccount/key:Key::aks-service-account-key
azure-native:network:PrivateZone                             urn:pulumi:dev::infrastructure::azure-native:network:PrivateZone::pgsql-private-zone
azure-native:network:VirtualNetwork                          urn:pulumi:dev::infrastructure::azure-native:network:VirtualNetwork::crystal-dev
azure-native:network:PublicIPAddress                         urn:pulumi:dev::infrastructure::azure-native:network:PublicIPAddress::bastion-ip
azure-native:network:VirtualNetworkLink                      urn:pulumi:dev::infrastructure::azure-native:network:VirtualNetworkLink::vnet-dns-link
azure-native:network:Subnet                                  urn:pulumi:dev::infrastructure::azure-native:network:Subnet::subnet-1
azure-native:network:Subnet                                  urn:pulumi:dev::infrastructure::azure-native:network:Subnet::subnet-2
azure-native:network:Subnet                                  urn:pulumi:dev::infrastructure::azure-native:network:Subnet::subnet-0
azure-native:dbforpostgresql/v20221201:Server                urn:pulumi:dev::infrastructure::azure-native:dbforpostgresql/v20221201:Server::crystal-dev
azure-native:network:NetworkInterface                        urn:pulumi:dev::infrastructure::azure-native:network:NetworkInterface::bastion-nic
azure-native:containerservice:ManagedCluster                 urn:pulumi:dev::infrastructure::azure-native:containerservice:ManagedCluster::crystal-dev
azure-native:compute:VirtualMachine                          urn:pulumi:dev::infrastructure::azure-native:compute:VirtualMachine::bastion
pulumi:providers:kubernetes                                  urn:pulumi:dev::infrastructure::pulumi:providers:kubernetes::k8s-provider
custom:flux:Flux                                             urn:pulumi:dev::infrastructure::custom:flux:Flux::flux
kubernetes:yaml:ConfigGroup                                  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup::flux-sync
kubernetes:yaml:ConfigGroup                                  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup::flux-install
tls:index/privateKey:PrivateKey                              urn:pulumi:dev::infrastructure::custom:flux:Flux$tls:index/privateKey:PrivateKey::flux-ssh-key
gitlab:index/repositoryFile:RepositoryFile                   urn:pulumi:dev::infrastructure::custom:flux:Flux$gitlab:index/repositoryFile:RepositoryFile::flux-sync
gitlab:index/repositoryFile:RepositoryFile                   urn:pulumi:dev::infrastructure::custom:flux:Flux$gitlab:index/repositoryFile:RepositoryFile::kustomize
gitlab:index/repositoryFile:RepositoryFile                   urn:pulumi:dev::infrastructure::custom:flux:Flux$gitlab:index/repositoryFile:RepositoryFile::flux-install
kubernetes:core/v1:Namespace                                 urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Namespace::flux-system
kubernetes:core/v1:ServiceAccount                            urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:ServiceAccount::flux-system/helm-controller
kubernetes:core/v1:ServiceAccount                            urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:ServiceAccount::flux-system/notification-controller
kubernetes:networking.k8s.io/v1:NetworkPolicy                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:networking.k8s.io/v1:NetworkPolicy::flux-system/allow-scraping
kubernetes:core/v1:ServiceAccount                            urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:ServiceAccount::flux-system/source-controller
kubernetes:core/v1:ServiceAccount                            urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:ServiceAccount::flux-system/kustomize-controller
kubernetes:core/v1:Service                                   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service::flux-system/webhook-receiver
kubernetes:networking.k8s.io/v1:NetworkPolicy                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:networking.k8s.io/v1:NetworkPolicy::flux-system/allow-webhooks
kubernetes:networking.k8s.io/v1:NetworkPolicy                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:networking.k8s.io/v1:NetworkPolicy::flux-system/allow-egress
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole          urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::crd-controller-flux-system
kubernetes:core/v1:Service                                   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service::flux-system/source-controller
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::providers.notification.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::helmrepositories.source.toolkit.fluxcd.io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cluster-reconciler-flux-system
kubernetes:core/v1:Service                                   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:core/v1:Service::flux-system/notification-controller
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::alerts.notification.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::buckets.source.toolkit.fluxcd.io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding   urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::crd-controller-flux-system
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::ocirepositories.source.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::receivers.notification.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::helmreleases.helm.toolkit.fluxcd.io
kubernetes:apps/v1:Deployment                                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1:Deployment::flux-system/notification-controller
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::helmcharts.source.toolkit.fluxcd.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::gitrepositories.source.toolkit.fluxcd.io
gitlab:index/deployKey:DeployKey                             urn:pulumi:dev::infrastructure::custom:flux:Flux$gitlab:index/deployKey:DeployKey::flux-key
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition  urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::kustomizations.kustomize.toolkit.fluxcd.io
kubernetes:apps/v1:Deployment                                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1:Deployment::flux-system/source-controller
kubernetes:apps/v1:Deployment                                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1:Deployment::flux-system/helm-controller
kubernetes:apps/v1:Deployment                                urn:pulumi:dev::infrastructure::custom:flux:Flux$kubernetes:yaml:ConfigGroup$kubernetes:apps/v1:Deployment::flux-system/kustomize-controller
kubernetes:core/v1:Secret                                    urn:pulumi:dev::infrastructure::kubernetes:core/v1:Secret::docker-secret

Found no pending operations associated with dev

Backend        
Name           mac-pro-mattia
URL            s3://crystal-azure-pulumi
User           mattia.devivo@igenius.ai
Organizations  

Dependencies:
NAME                  VERSION
@types/node           16.18.27
@worawat/flux         0.22.2
@pulumi/azuread       5.37.0
@pulumi/tls           4.10.0
@pulumi/gitlab        5.0.2
@pulumi/kubernetes    3.27.1
@pulumi/pulumi        3.66.0
@pulumi/random        4.13.0
@pulumi/azure-native  1.102.0
@pulumi/gcp           6.56.0

Pulumi locates its logs in /var/folders/81/r9pvsdlx2n1378qhpf7hjg_40000gp/T/ by default

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by mattiadevivo**
Fix configuration points/variable names:
- base_url -> baseUrl
- cacert_file -> cacertFile

### CODE REVIEW

**Comment by onlynone** [comment]
I noticed other property names with underscores in: https://github.com/pulumi/pulumi-gitlab/blob/master/provider/cmd/pulumi-resource-gitlab/bridge-metadata.json#L2551 under `gitlab:index:Provider` and `renamedConfigProperties`:


        {
            "baseUrl": "base_url",
            "cacertFile": "cacert_file",
            "clientCert": "client_cert",
            "clientKey": "client_key",
            "earlyAuthCheck": "early_auth_check"
        }

Do those also need to be addressed?

**Comment by qerub** [comment]
I'm not a maintainer, but isn't the issue that the Terraform bridge isn't applying the renaming configuration rather than incorrect documentation in the README?

**Comment by t0yv0** [comment]
Thank you for this PR! We'll need to verify first if we haven't accidentally regressed here, and if that is the case perhaps restore the ability to parse the original casing of this configuration values. My team will be having a look.

**Comment by t0yv0** [comment]
There are the preferred spellings so I'm happy to accept the PR. I could not reproduce the issue though of older spellings like base_url  being ignored. It seems to me that it picks up either base_url or baseUrl and treats them identically.

**Pull request merged**
